# Generated by Django 5.1.5 on 2025-02-07 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='listing_WatchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
